In [2]:
import pandas as pd
melb_df = pd.read_csv('/home/dana/ide/project_0/data/melb_data_12.csv')
melb_df.head()
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  object
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  object
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  object
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  int64
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  int64
 24  StreetType       13580 non-null  object
 25  Weekend          13580 non-null  int64
dtypes: float64(8), int64(10), object(8)
memory usage: 2.7+ MB

In [3]:
melb_df['Date']=pd.to_datetime(melb_df['Date'])
display(melb_df['Date'])
def whichquarter(month):
    if 1<= month <=3:
        return 'quarter1'
    elif 4<= month <=6:   
        return 'quarter2'
    elif 7<= month <=9:
        return 'quarter3'
    return 'quarter4'   
melb_df['quarter']=melb_df['Date'].dt.month.apply(whichquarter)
melb_df['quarter'].value_counts()
melb_df.drop('quarter', axis=1, inplace=True)

0       2016-03-12
1       2016-04-02
2       2017-04-03
3       2017-04-03
4       2016-04-06
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

In [4]:
cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car']
max_unique_count = 150 
for col in melb_df.columns: 
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: 
        melb_df[col] = melb_df[col].astype('category') 
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  category
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  category
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  category
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  category
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  category
 24  StreetType       13580 non-null  category
 25  Weekend          13580 non-null  category
dtypes: category(10), datetime64[ns](1), float64(8), int64(7)
memory usage: 1.8 MB

None

In [5]:
#sort_values()
#by — имя или список имён столбцов, по значениям которых производится сортировка.
#axis — ось, по которой производится сортировка (0 — строки, 1 — столбцы). По умолчанию сортировка производится по строкам.
#ascending — сортировка по возрастанию (от меньшего к большему). По умолчанию параметр выставлен на True, для сортировки по убыванию (от большего к меньшему) необходимо выставить его на False.
#ignore_index — создаются ли новые индексы в таблице. По умолчанию выставлен на False и сохраняет индексы изначальной таблицы.
#inplace — производится ли замена исходной таблицы на отсортированную. По умолчанию параметр выставлен на False, то есть замены не производится. Чтобы переопределить исходную таблицу на отсортированную, необходимо выставить этот параметр на True.

melb_df.sort_values(by='Price').head(10)
melb_df.sort_values(by='Date', ascending=False)
melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']] #каждая 10 строка

mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

        Date  AreaRatio
0 2016-07-26  -0.974922
1 2016-09-24  -0.971831
2 2016-11-27  -0.953608
3 2016-12-11  -0.945946
4 2017-08-04  -0.947368
5 2017-08-04  -0.970874

In [6]:
melb_df.sort_values(by='AreaRatio', ascending=False, ignore_index=True).loc[1558, ['BuildingArea']]

BuildingArea    77.0
Name: 1558, dtype: object

In [7]:
masktype = melb_df['Type'] == 'townhouse'
maskroom = melb_df['Rooms'] > 2
melb_df[maskroom & masktype].sort_values(
    by=['Rooms','MeanRoomsSquare'],
    ascending=[True, False],
    ignore_index=True
).loc[18,['Price']]

Price    1300000.0
Name: 18, dtype: object

In [8]:
# groupby()
#by — имя или список имён столбцов, по которым производится группировка.
#axis — ось, по которой производится группировка (0 — строки, 1 — столбцы). По умолчанию группировка производится по строкам.
#as_index — добавляется ли дополнительный индекс к таблице. По умолчанию установлен на True.

In [9]:
melb_df.groupby(by='Type', observed=True).mean(numeric_only=True)
melb_df.groupby('Type', observed=True)['Price'].mean()
melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

melb_df.groupby('MonthSale')['Price'].agg(
    ['count', 'mean', 'max']
).sort_values(by='count', ascending=False)

melb_df.groupby('MonthSale')['Price'].agg('describe')

melb_df.groupby('Regionname')['SellerG'].agg(
    		['nunique', set]
)

/tmp/ipykernel_4535/213555294.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)
/tmp/ipykernel_4535/213555294.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('MonthSale')['Price'].agg(
/tmp/ipykernel_4535/213555294.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('MonthSale')['Price'].agg('describe')
/tmp/ipykernel_4535/213555294.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['SellerG'].agg(

,nunique,set
Regionname,,
Eastern Metropolitan,26,"{Stockdale, Fletchers, Gary, Woodards, other, ..."
Eastern Victoria,11,"{C21, Ray, Fletchers, other, Harcourts, HAR, E..."
Northern Metropolitan,40,"{Stockdale, Fletchers, YPA, Jas, Eview, Raine,..."
Northern Victoria,11,"{LITTLE, Ray, other, YPA, HAR, hockingstuart, ..."
South-Eastern Metropolitan,25,"{Stockdale, Fletchers, Gary, Eview, O'Brien, W..."
Southern Metropolitan,38,"{Stockdale, Fletchers, Gary, Jas, Eview, O'Bri..."
Western Metropolitan,34,"{Stockdale, YPA, Jas, O'Brien, Raine, Woodards..."
Western Victoria,6,"{Ray, other, YPA, HAR, hockingstuart, Raine}"

In [10]:
melb_df.groupby('Rooms', observed=True)['Price'].mean().sort_values(ascending=False)
melb_df.groupby('Regionname', observed=True)['Lattitude'].std().sort_values()

Regionname
Western Victoria              0.011579
Southern Metropolitan         0.043080
Eastern Metropolitan          0.047890
Northern Metropolitan         0.049639
Western Metropolitan          0.051251
South-Eastern Metropolitan    0.073411
Northern Victoria             0.084455
Eastern Victoria              0.147067
Name: Lattitude, dtype: float64

In [11]:
#мой варинат, подходит для месяцев без конкретных дат
melb_df['Date']=pd.to_datetime(melb_df['Date'])
lowmonth=(melb_df['Date'].dt.year ==2017) & (melb_df['Date'].dt.month.between(5,9))
melb_df[lowmonth].groupby('SellerG',observed=True)['Price'].sum().sort_values()
#вариант из курса(правильный)для конкретных дат с 1 по 1
date1 = pd.to_datetime('2017-05-01')
date2 = pd.to_datetime('2017-09-01')
mask = (date1 <= melb_df['Date']) & (melb_df['Date']<= date2)
melb_df[mask].groupby('SellerG')['Price'].sum().sort_values(ascending=True)

/tmp/ipykernel_4535/2583530686.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df[mask].groupby('SellerG')['Price'].sum().sort_values(ascending=True)

SellerG
LITTLE             2742000.0
Cayzer             4439000.0
Burnham            4550500.0
Moonee             7328000.0
Thomson            8332000.0
Bells              8656000.0
Alexkarbon        10985000.0
McDonald          14637500.0
Rendina           15422276.0
Nick              16890000.0
Douglas           18341000.0
Buckingham        19033000.0
C21               19515000.0
Eview             19791500.0
Collins           20217000.0
Philip            22051800.0
Chisholm          23225000.0
Williams          23297000.0
Love              23365500.0
Purplebricks      23401000.0
O'Brien           23855508.0
HAR               25568000.0
Village           26473000.0
RW                29261000.0
Raine             30687700.0
Stockdale         35409800.0
Sweeney           36882750.0
Gary              39138400.0
Hodges            43231000.0
YPA               46354350.0
Miles             47582000.0
Kay               48569500.0
RT                50498000.0
Brad              55955000.0
Jas               59281600.0
Harcourts         68720250.0
McGrath           78386500.0
Greg              85621000.0
Woodards          85977500.0
Noel              88129800.0
Fletchers        108847700.0
Biggin           110429500.0
Buxton           219104000.0
Ray              249572986.0
Marshall         253957888.0
hockingstuart    282834310.0
Barry            296723050.0
other            365038432.0
Nelson           379767500.0
Jellis           414121833.0
Name: Price, dtype: float64

In [14]:
melb_df.groupby('Rooms')[['Price', 'BuildingArea']].median()
melb_df.groupby(['Rooms', 'Type'])['Price'].mean()
melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

/tmp/ipykernel_4535/1236765415.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(['Rooms', 'Type'])['Price'].mean()
/tmp/ipykernel_4535/1236765415.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

Type          house     townhouse          unit
Rooms
1      8.668655e+05  5.927045e+05  3.899289e+05
2      1.017238e+06  7.101585e+05  6.104905e+05
3      1.109233e+06  9.847087e+05  8.505963e+05
4      1.462283e+06  1.217092e+06  1.037476e+06
5      1.877327e+06  1.035000e+06           NaN
6      1.869508e+06           NaN  5.200000e+05
7      1.920700e+06           NaN           NaN
8      1.510286e+06           NaN  2.250000e+06
10     9.000000e+05           NaN           NaN

pivot_table()
values — имя столбца, по которому необходимо получить сводные данные, применяя агрегирующую функцию;
index — имя столбца, значения которого станут строками сводной таблицы;
columns — имя столбца, значения которого станут столбцами сводной таблицы;
aggfunc — имя или список имён агрегирующих функций (по умолчанию — подсчёт среднего, 'mean');
fill_value — значение, которым необходимо заполнить пропуски (по умолчанию пропуски не заполняются).

In [23]:
melb_df.pivot_table(
    values='Price',
    index='Rooms',
    columns='Type',
    fill_value=0
).round()

melb_df.pivot_table(
    values='Price',
    index='Regionname',
    columns='Weekend',
    aggfunc='count'
)

melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)

melb_df.pivot_table(
    values='Price',
    index=['Method','Type'],
    columns='Regionname',
    aggfunc='median',
    fill_value=0
)

pivot = melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)
pivot.columns
display(pivot['mean']['unit'])
mask = pivot['mean']['house'] < pivot['median']['house']
filtered_pivot = pivot[mask]
display(filtered_pivot)
print(list(filtered_pivot.index))

/tmp/ipykernel_4535/1690911986.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
/tmp/ipykernel_4535/1690911986.py:8: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
/tmp/ipykernel_4535/1690911986.py:15: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
/tmp/ipykernel_4535/1690911986.py:15: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
/tmp/ipykernel_4535/1690911986.py:23: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
/tmp/ipykernel_4535/1690911986.py:31: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(
/tmp/ipykernel_4535/1690911986.py:31: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(

Regionname
Eastern Metropolitan          330.444444
Eastern Victoria              295.333333
Northern Metropolitan         495.026538
Northern Victoria               0.000000
South-Eastern Metropolitan    357.864865
Southern Metropolitan         466.380245
Western Metropolitan          557.637232
Western Victoria                0.000000
Name: unit, dtype: float64

                      median                        mean              \
Type                   house townhouse  unit       house   townhouse
Regionname
Southern Metropolitan  586.0     246.0   0.0  569.643881  278.858824
Western Metropolitan   531.0     198.0  62.0  507.883406  244.560669


Type                         unit
Regionname
Southern Metropolitan  466.380245
Western Metropolitan   557.637232

['Southern Metropolitan', 'Western Metropolitan']

In [31]:
import numpy as np
mser = pd.Series(
    np.random.rand(8),
	index=[['white','white','white','blue','blue','red','red','red'], 
           ['up','down','right','up','down','up','down','left']])
display(mser)
print(mser.index)

mframe = pd.DataFrame(
    np.random.randn(16).reshape(4,4),
    index=[['white','white','red','red'], ['up','down','up','down']],
    columns=[['pen','pen','paper','paper'],[1,2,1,2]]
)
display(mframe)

white  up       0.945955
       down     0.876532
       right    0.054627
blue   up       0.342571
       down     0.727632
red    up       0.440041
       down     0.139715
       left     0.120701
dtype: float64

MultiIndex([('white',    'up'),
            ('white',  'down'),
            ('white', 'right'),
            ( 'blue',    'up'),
            ( 'blue',  'down'),
            (  'red',    'up'),
            (  'red',  'down'),
            (  'red',  'left')],
           )

                 pen               paper
                   1         2         1         2
white up   -0.975465  0.830729  1.136559  1.882592
      down  0.473305  0.773367 -1.122965 -0.435734
red   up   -0.114517  0.388658  0.256715  0.355749
      down -1.532972  0.335515 -0.544598  0.266347

In [39]:
melb_df.pivot_table(
    values='BuildingArea',
    index='Rooms',
    columns='Type',
    aggfunc='median',
    fill_value=0
).idxmax()

melb_df.pivot_table(
    values='Price',
    index='SellerG',
    columns='Type',
    aggfunc='median',
    fill_value=0
).sort_values(by='unit', ascending=False)

/tmp/ipykernel_4535/2959499423.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
/tmp/ipykernel_4535/2959499423.py:9: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

Type               house  townhouse      unit
SellerG
Nick           2025000.0   780000.0  900000.0
Marshall       1975000.0  1408500.0  715000.0
Cayzer         1505000.0  1450000.0  707500.0
Kay            2220000.0  1365000.0  695000.0
Noel           1400500.0   990000.0  693250.0
Buxton         1323750.0  1030000.0  670000.0
Fletchers      1390000.0  1238000.0  653000.0
Chisholm       1520000.0   950000.0  640000.0
Philip         1035000.0   701000.0  636000.0
RT             1640000.0  1400000.0  630000.0
C21             836500.0   768750.0  625500.0
RW              870000.0   630500.0  625500.0
Moonee          806000.0   715000.0  622000.0
O'Brien         737504.0   430000.0  618500.0
Hodges         1500000.0  1105000.0  605500.0
Eview           760000.0   597500.0  602000.0
Woodards       1261000.0   865500.0  600000.0
Collins        1566500.0   930000.0  592000.0
Jellis         1505000.0  1052000.0  591750.0
Purplebricks    810000.0   927500.0  582500.0
Williams       1161000.0   735000.0  577000.0
hockingstuart  1055000.0   935000.0  566000.0
Alexkarbon     1036250.0   935000.0  560000.0
Miles          1090000.0   721500.0  555000.0
Buckingham      830000.0   820000.0  553000.0
Gary           1370000.0   993500.0  550000.0
Biggin         1151750.0   675000.0  548000.0
Greg           1330000.0   900000.0  547500.0
McGrath        1250000.0   810000.0  542500.0
other           901000.0   840500.0  535000.0
Nelson         1055000.0   730000.0  530000.0
HAR             695000.0        0.0  518000.0
McDonald       1242500.0        0.0  502500.0
Barry           830000.0   727500.0  502000.0
Harcourts       740000.0   653750.0  500000.0
Ray             900000.0   650000.0  497500.0
Thomson        1177000.0   500000.0  495000.0
Douglas         684000.0   500000.0  494500.0
Brad            875000.0   700000.0  465000.0
Rendina        1190000.0   750000.0  459000.0
Bells           692500.0   430500.0  457500.0
Jas             935000.0   699000.0  455000.0
Raine           745000.0   608000.0  447500.0
LITTLE          970000.0   800000.0  447000.0
YPA             596250.0   498500.0  443500.0
Love            780000.0   846000.0  440000.0
Village         973500.0   727500.0  420000.0
Stockdale       715500.0   550000.0  410000.0
Sweeney         850000.0   728000.0  381000.0
Burnham         922500.0        0.0  305000.0