In [1]:
import pandas as pd
melb_df = pd.read_csv('/home/dana/ide/project_0/data/melb_data_12.csv')
melb_df.head()
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  object
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  object
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  object
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  int64
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  int64
 24  StreetType       13580 non-null  object
 25  Weekend          13580 non-null  int64
dtypes: float64(8), int64(10), object(8)
memory usage: 2.7+ MB

In [2]:
melb_df['Date']=pd.to_datetime(melb_df['Date'])
display(melb_df['Date'])
def whichquarter(month):
    if 1<= month <=3:
        return 'quarter1'
    elif 4<= month <=6:   
        return 'quarter2'
    elif 7<= month <=9:
        return 'quarter3'
    return 'quarter4'   
melb_df['quarter']=melb_df['Date'].dt.month.apply(whichquarter)
melb_df['quarter'].value_counts()
melb_df.drop('quarter', axis=1, inplace=True)

0       2016-03-12
1       2016-04-02
2       2017-04-03
3       2017-04-03
4       2016-04-06
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

In [3]:
cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car']
max_unique_count = 150 
for col in melb_df.columns: 
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: 
        melb_df[col] = melb_df[col].astype('category') 
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  category
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  category
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  category
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  category
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  category
 24  StreetType       13580 non-null  category
 25  Weekend          13580 non-null  category
dtypes: category(10), datetime64[ns](1), float64(8), int64(7)
memory usage: 1.8 MB

None

In [4]:
#sort_values()
#by — имя или список имён столбцов, по значениям которых производится сортировка.
#axis — ось, по которой производится сортировка (0 — строки, 1 — столбцы). По умолчанию сортировка производится по строкам.
#ascending — сортировка по возрастанию (от меньшего к большему). По умолчанию параметр выставлен на True, для сортировки по убыванию (от большего к меньшему) необходимо выставить его на False.
#ignore_index — создаются ли новые индексы в таблице. По умолчанию выставлен на False и сохраняет индексы изначальной таблицы.
#inplace — производится ли замена исходной таблицы на отсортированную. По умолчанию параметр выставлен на False, то есть замены не производится. Чтобы переопределить исходную таблицу на отсортированную, необходимо выставить этот параметр на True.

melb_df.sort_values(by='Price').head(10)
melb_df.sort_values(by='Date', ascending=False)
melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']] #каждая 10 строка

mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

        Date  AreaRatio
0 2016-07-26  -0.974922
1 2016-09-24  -0.971831
2 2016-11-27  -0.953608
3 2016-12-11  -0.945946
4 2017-08-04  -0.947368
5 2017-08-04  -0.970874

In [5]:
melb_df.sort_values(by='AreaRatio', ascending=False, ignore_index=True).loc[1558, ['BuildingArea']]

BuildingArea    77.0
Name: 1558, dtype: object

In [6]:
masktype = melb_df['Type'] == 'townhouse'
maskroom = melb_df['Rooms'] > 2
melb_df[maskroom & masktype].sort_values(
    by=['Rooms','MeanRoomsSquare'],
    ascending=[True, False],
    ignore_index=True
).loc[18,['Price']]

Price    1300000.0
Name: 18, dtype: object

In [13]:
melb_df.groupby(by='Type', observed=True).mean(numeric_only=True)
melb_df.groupby('Type', observed=True)['Price'].mean()
melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

melb_df.groupby('MonthSale')['Price'].agg(
    ['count', 'mean', 'max']
).sort_values(by='count', ascending=False)

melb_df.groupby('MonthSale')['Price'].agg('describe')

melb_df.groupby('Regionname')['SellerG'].agg(
    		['nunique', set]
)

/tmp/ipykernel_5346/213555294.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)
/tmp/ipykernel_5346/213555294.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('MonthSale')['Price'].agg(
/tmp/ipykernel_5346/213555294.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('MonthSale')['Price'].agg('describe')
/tmp/ipykernel_5346/213555294.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['SellerG'].agg(

,nunique,set
Regionname,,
Eastern Metropolitan,26,"{Love, McGrath, Stockdale, Ray, Purplebricks, ..."
Eastern Victoria,11,"{O'Brien, Ray, McGrath, Eview, hockingstuart, ..."
Northern Metropolitan,40,"{Love, McGrath, Jas, Collins, McDonald, Stockd..."
Northern Victoria,11,"{Ray, McGrath, YPA, hockingstuart, Buckingham,..."
South-Eastern Metropolitan,25,"{O'Brien, McGrath, Stockdale, Thomson, Ray, Gr..."
Southern Metropolitan,38,"{O'Brien, McGrath, Jas, Collins, Cayzer, Thoms..."
Western Metropolitan,34,"{O'Brien, McGrath, Jas, Bells, McDonald, Stock..."
Western Victoria,6,"{Ray, YPA, hockingstuart, HAR, Raine, other}"

In [ ]:
melb_df.groupby('Rooms', observed=True)['Price'].mean().sort_values(ascending=False)
melb_df.groupby('Regionname', observed=True)['Lattitude'].std().sort_values()

Regionname
Western Victoria              0.011579
Southern Metropolitan         0.043080
Eastern Metropolitan          0.047890
Northern Metropolitan         0.049639
Western Metropolitan          0.051251
South-Eastern Metropolitan    0.073411
Northern Victoria             0.084455
Eastern Victoria              0.147067
Name: Lattitude, dtype: float64

In [ ]:
#мой варинат, подходит для месяцев без конкретных дат
melb_df['Date']=pd.to_datetime(melb_df['Date'])
lowmonth=(melb_df['Date'].dt.year ==2017) & (melb_df['Date'].dt.month.between(5,9))
melb_df[lowmonth].groupby('SellerG',observed=True)['Price'].sum().sort_values()
#вариант из курса(правильный)для конкретных дат с 1 по 1
date1 = pd.to_datetime('2017-05-01')
date2 = pd.to_datetime('2017-09-01')
mask = (date1 <= melb_df['Date']) & (melb_df['Date']<= date2)
melb_df[mask].groupby('SellerG')['Price'].sum().sort_values(ascending=True)

SellerG
LITTLE             2742000.0
Burnham            4550500.0
Moonee             7328000.0
Thomson            8332000.0
Cayzer             8356000.0
Bells             10876000.0
Alexkarbon        10985000.0
McDonald          14637500.0
Rendina           17252276.0
Nick              19505000.0
Douglas           21676000.0
Buckingham        22238000.0
Collins           23162000.0
Eview             24374500.0
Chisholm          25225000.0
C21               25750500.0
Purplebricks      26792500.0
Williams          27711000.0
Philip            28281300.0
Village           28728000.0
Love              29542500.0
O'Brien           32019508.0
RW                36223500.0
HAR               37733500.0
Gary              39138400.0
Raine             39309700.0
Stockdale         44470800.0
Sweeney           44994750.0
Hodges            50871000.0
Miles             53573000.0
Kay               55949500.0
YPA               59371850.0
RT                61654500.0
Brad              67373500.0
Jas               67735600.0
Harcourts         80979750.0
McGrath           92666500.0
Greg              98734000.0
Woodards         102533688.0
Noel             103985800.0
Biggin           117135500.0
Fletchers        131233700.0
Buxton           277954000.0
Ray              309719086.0
Marshall         335933888.0
hockingstuart    337258810.0
Barry            343592438.0
other            442003931.0
Nelson           444669601.0
Jellis           520459833.0
Name: Price, dtype: float64