In [2]:
import pandas as pd
ratings1 = pd.read_csv('/home/dana/ide/project_0/data/ratings1.csv')
ratings2 = pd.read_csv('/home/dana/ide/project_0/data/ratings2.csv')
dates = pd.read_csv('/home/dana/ide/project_0/data/dates.csv')
movies = pd.read_csv('/home/dana/ide/project_0/data/movies.csv')

In [14]:
movies.nunique()
ratings1.nunique()
dates = pd.to_datetime(dates)
dates.dt.year.value_counts()

date
2000    10061
2017     8198
2007     7114
2016     6703
2015     6616
2018     6418
1996     6040
2005     5813
2012     4656
2008     4351
2009     4158
2006     4059
2003     4014
2001     3922
2002     3478
2004     3279
1999     2439
2010     2301
1997     1916
2011     1690
2013     1664
2014     1439
1998      507
Name: count, dtype: int64

In [20]:
#concat()
#objs — список объектов DataFrame ([df1, df2,…]), которые должны быть сконкатенированы;
#axis — ось определяет направление конкатенации: 0 — конкатенация по строкам (по умолчанию), 1 — конкатенация по столбцам;
#join — либо inner (пересечение), либо outer (объединение); рассмотрим этот момент немного позже;
#ignore_index — по умолчанию установлено значение False, которое позволяет значениям индекса оставаться такими, какими они были в исходных данных.
#Если установлено значение True, параметр будет игнорировать исходные значения и повторно назначать значения индекса в последовательном порядке.

ratings = pd.concat(
    [ratings1, ratings2],
    ignore_index=True
   )
display(ratings)

print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице dates: ', dates.shape[0])
print(ratings.shape[0] == dates.shape[0])

display(ratings1.tail(1))
display(ratings2.head(1))

ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])

ratings_dates = pd.concat([ratings, dates], axis=1)
display(ratings_dates.tail(7))

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

Число строк в таблице ratings:  100837
Число строк в таблице dates:  100836
False

       userId  movieId  rating
40000     274     5621     2.0

   userId  movieId  rating
0     274     5621     2.0

Число строк в таблице ratings:  100836

        userId  movieId  rating                date
100829     610   164179     5.0 2017-05-03 21:07:11
100830     610   166528     4.0 2017-05-04 06:29:25
100831     610   166534     4.0 2017-05-03 21:53:22
100832     610   168248     5.0 2017-05-03 22:21:31
100833     610   168250     5.0 2017-05-08 19:50:47
100834     610   168252     5.0 2017-05-03 21:19:12
100835     610   170875     3.0 2017-05-03 21:20:15